# Generated by Django 4.2.2 on 2023-06-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_createprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createprofile',
        ),
    ]
