# Generated by Django 4.2.2 on 2023-06-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_addblog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addblog',
        ),
    ]
